#AKS deployment file
apiVersion : apps/v1
kind: Deployment
metadata:
  name: uwazi-orchestrator 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uwazi-orchestrator
  template:
    metadata:
      labels:
        app: uwazi-orchestrator
    spec:
      nodeSelector:
        "kubernetes.io/os": linux     
      containers:
        - name: uwaziorchestrator
          image: ghq03532uwaziweudevacr.azurecr.io/uwaziorchestrator
          ports:
          - containerPort: 80